services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db
            - redis
        container_name: laravel_api
        environment:
            DB_CONNECTION: pgsql
            DB_HOST: db
            DB_PORT: 5432
            DB_DATABASE: bank
            DB_USERNAME: alireza
            DB_PASSWORD: alireza123
            REDIS_CLIENT: predis
            REDIS_HOST: redis
            REDIS_PORT: 6379
            APP_TIMEZONE: Asia/Tehran
            CACHE_STORE: redis
            REDIS_CACHE_CONNECTION: cache
            FEE: 500
            MAX_TRANSACTION: 50000000
            OCTANE_SERVER: swoole
            APP_KEY: 'base64:4Io9Jl2vGhsEzOSbLvfZfeUl3/jtG8bdi/fUFKR16xo='
            APP_ENV: production

        ports:
            - "8001:8000"

        restart: always


    db:
        image: hub.hamdocker.ir/postgres:16.3
        container_name: bank_database
        environment:
            POSTGRES_USER: alireza
            POSTGRES_PASSWORD: alireza123
            POSTGRES_DB: bank
            TZ: Asia/Tehran
            PGTZ: Asia/Tehran

        restart: always

        volumes:
            - db-data:/var/lib/postgresql/data

    redis:
        image: hub.hamdocker.ir/redis:7.2
        container_name: bank_redis
        restart: always

volumes:
  db-data:

